package server.machines;



public enum NautintojuomaMachine {

    SILO1, SILO2, SILO3, SILO4, SILO_LOADER, PROC_LOADER1, PROC_LOADER2,
    PROCESSOR1, PROCESSOR2, PROCESSOR3, TANK1, TANK2, TANK3, TANK4

}
