package server.machines;



public enum NautintojuomaMachine {

    SILO1, SILO2, SILO3, SILO4, SILO_LOADER, PROC_LOADER1, PROC_LOADER2,
    PROCESSOR1, PROCESSOR2, PROCESSOR3, TANK1, TANK2, TANK3, TANK4, TANK5,
    TANK6, TANK7, TANK8, TANK9, TANK10, PUMP1, PUMP2, BOTTLING_PUMP1, BOTTLING_PUMP2

}
